### ISSUE TITLE
How to run sweep

### ISSUE THREAD

**Issue by Rane90** [nivha/dataset_reconstruction#2]
Hi,

Thank you for providing this repository.

Suppose I've trained a model, and would like to reconstruct with it. How would I run a sweep to search for the correct hyperparameters?
I saw, in `reconstruction_mnist.ipynb` that you can read an exising sweep:

```
# in case you have your own sweep:
sweep_id = 'uvl74ek9'
sweeps_dir = './data/sweeps/'
sweep = analysis_utils.read_sweep(sweeps_dir, sweep_id, name=None, problem='mnist_odd_even')
analysis_utils.download_sweep_results_from_wandb(sweep, max_runs_to_download=100)
X = analysis_utils.get_all_reconstruction_outputs(sweep, verbose=True)

```
But again, how would I initially run it?

**Comment by nivha** [comment]
Hi @Rane90,

We used weights and biases (W&B) to run sweeps over the hyperparameters of our optimization scheme (the 4 hyperparameters are the leraning rate, the scale of the initialized x_i's, the "alpha" of the modified Relu and the minimal lambda value). That's why we call it a sweep.. In order to run your own sweep you should get your W&B user and configure a sweep there, and run it on your own cluster..

If you find it helpful, I can share with you the configuration that we used for example for one of our sweeps in W&B:

```
parameters:
  data_per_class_train:
    value: 250
  extraction_data_amount_per_class:
    value: 500
  extraction_epochs:
    value: 50000
  extraction_evaluate_rate:
    value: 1000
  extraction_init_scale:
    distribution: log_uniform_values
    max: 0.1
    min: 1e-06
  extraction_lr:
    distribution: log_uniform_values
    max: 1
    min: 1e-05
  extraction_min_lambda:
    distribution: uniform
    max: 0.5
    min: 0.01
  extraction_model_relu_alpha:
    distribution: uniform
    max: 500
    min: 10
  model_hidden_list:
    value: '[1000,1000]'
  model_init_list:
    value: '[0.001,0.001]'
  pretrained_model_path:
    value: path_to_trained_model.pth
  problem:
    value: cifar10_vehicles_animals
  proj_name:
    value: some_name_example_sweep
  run_mode:
    value: reconstruct
  wandb_active:
    value: true
program: Main.py

```

Then, after the sweep has finished (we usually did about 100-300 runs per sweep), then you can use our code to download the results.

**Comment by nivha** [comment]
Hi @Rane90,

We used weights and biases (W&B) to run sweeps over the hyperparameters of our optimization scheme (the 4 hyperparameters are the leraning rate, the scale of the initialized x_i's, the "alpha" of the modified Relu and the minimal lambda value). That's why we call it a sweep.. In order to run your own sweep you should get your W&B user and configure a sweep there, and run it on your own cluster..

If you find it helpful, I can share with you the configuration that we used for example for one of our sweeps in W&B:

```
parameters:
  data_per_class_train:
    value: 250
  extraction_data_amount_per_class:
    value: 500
  extraction_epochs:
    value: 50000
  extraction_evaluate_rate:
    value: 1000
  extraction_init_scale:
    distribution: log_uniform_values
    max: 0.1
    min: 1e-06
  extraction_lr:
    distribution: log_uniform_values
    max: 1
    min: 1e-05
  extraction_min_lambda:
    distribution: uniform
    max: 0.5
    min: 0.01
  extraction_model_relu_alpha:
    distribution: uniform
    max: 500
    min: 10
  model_hidden_list:
    value: '[1000,1000]'
  model_init_list:
    value: '[0.001,0.001]'
  pretrained_model_path:
    value: path_to_trained_model.pth
  problem:
    value: cifar10_vehicles_animals
  proj_name:
    value: some_name_example_sweep
  run_mode:
    value: reconstruct
  wandb_active:
    value: true
program: Main.py

```

Then, after the sweep has finished (we usually did about 100-300 runs per sweep), then you can use our code to download the results.
